FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
# Copia o arquivo de projeto e restaura as dependências
COPY ["ApiMoniEquipamentosPesados.csproj", "./"]
RUN dotnet restore "./ApiMoniEquipamentosPesados.csproj"

# Copia todo o resto do código
COPY . .
WORKDIR "/src/."
RUN dotnet build "ApiMoniEquipamentosPesados.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ApiMoniEquipamentosPesados.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
# Comando para rodar a aplicação
ENTRYPOINT ["dotnet", "ApiMoniEquipamentosPesados.dll"]